export const AUTH = "[Auth]";

export const LOGIN_REQUEST = `${AUTH} LOGIN_REQUEST`;

export const REGISTER_REQUEST = `${AUTH} REGISTER_REQUEST`;

export const FETCH_AUTHENTICATED_USER = `${AUTH} FETCH_AUTHENTICATED_USER`;

export const FETCH_AUTHENTICATED_USER_SUCCESS = `${AUTH} FETCH_AUTHENTICATED_USER_SUCCESS`;
