export const AUTH = '[Auth]';

export const LOGIN_REQUEST = `${AUTH} LOGIN_REQUEST`;
export const SET_TOKEN = `${AUTH} SET_TOKEN`;
export const REGISTER_REQUEST = `${AUTH} REGISTER_REQUEST`;
export const FETCH_AUTHENTICATED_USER = `${AUTH} FETCH_AUTHENTICATED_USER`;
export const FETCH_AUTHENTICATED_USER_SUCCESS = `${AUTH} FETCH_AUTHENTICATED_USER_SUCCESS`;
export const GET_USER_FROM_URL_REQUEST = 'GET_USER_FROM_URL_REQUEST';
export const GET_USER_FROM_URL_SUCCESS = 'GET_USER_FROM_URL_SUCCESS';
